app/nephrosis/urls.py
from django.urls import path, re_path
from . import views

app_name = "nephrosis"

urlpatterns = [
    path('', views.index, name='index'),
    path('test<str:test_id>', views.patients, name="patients"),
    path('test<str:test_id>/detail/<int:patient_id>/', views.detail, name="detail"),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('sample', views.testview , name='test'),
]

app/website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', include('nephrosis.urls')),
    path('admin/', admin.site.urls),
]

# for debug
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

app/nephrosis/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser


class Patient(models.Model):
    patient_text = models.CharField(max_length=200)
    is_nephrosis = models.BooleanField()
    predict_is_nephrosis = models.BooleanField()
    nonnephs_proba = models.FloatField()
    nephs_proba = models.FloatField()

    def __str__(self):
        return self.patient_text


class Exp(models.Model):
    patient = models.ForeignKey(
        Patient,
        on_delete=models.CASCADE,
    )
    cond_exp = models.CharField(max_length=20)
    contribution = models.FloatField()

    # def __str__(self):
    #     return self.pk


class User(AbstractUser):
    pass

    def __str__(self):
        return self.username


class Result(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_prediction = models.BooleanField()
    is_correct = models.BooleanField()
    
    def __str__(self):
        return "patient:{} | user:{}".format(
            self.patient, self.user
        )


class Inspection(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    inspection_date = models.DateField()
    inspection_item = models.CharField(max_length=10)
    inspection_value = models.FloatField(null=True, blank=True)
    
    def __str__(self):
        return "name:{} | date:{} | item:{}".format(
        self.patient, str(self.inspection_date), self.inspection_item
        )

app/nephrosis/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields

# class NameForm(forms.Form):
#     your_name = forms.CharField(label='Your name', max_length=100)

app/nephrosis/views.py
# TODO:
# - [x]test task 1
# - test task 2

# FIXME:
# - test fixme 

from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required


from .models import Patient, Exp, Result, User, Inspection

from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy
from django.views import generic
 

class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'nephrosis/signup.html'

def testview(request):
    context = {"is_ajax":request.is_ajax()}
    return render(request, "nephrosis/test.html", context)

@login_required
def index(request):
    test_ids = ["A", "B", "C"]
    context = {
        "test_ids": test_ids
    }
    return render(request, "nephrosis/index.html", context)

# @login_required
def patients(request, test_id):
    # user・test_id毎に違う患者データセットを表示
    div = Patient.objects.count() // 3
    order_value = request.user.id % 3
    base_dict = {"A":0, "B":1, "C":2}
    start = ((base_dict[test_id] + order_value) % 3) * div
    end = start + div
    patient_list = get_list_or_404(Patient)[start:end]

    context = {
        "patient_list": patient_list,
        "test_id" : test_id,
    }
    return render(request, "nephrosis/patients.html", context)


# @login_required
def detail(request, patient_id, test_id):
    if request.is_ajax():
        user_is_nephs = request.POST["is_nephs"] == "nephs"
        patient_obj = get_object_or_404(Patient, pk=patient_id)
        is_correct = patient_obj.is_nephrosis == user_is_nephs
        defaults = {"user_prediction": user_is_nephs, "is_correct": is_correct}
        result, created = Result.objects.update_or_create(
            patient=patient_obj,
            user=request.user,
            defaults=defaults,
        )
        if user_is_nephs:
            return HttpResponse("現在の予測 : ネフローゼ")
        else:
            return HttpResponse("現在の予測 : 非ネフローゼ")
        # return HttpResponse("現在の予測 : ".format(request.POST["is_nephs"]))

    else:
        patient_obj = get_object_or_404(Patient, pk=patient_id)
        exp_list = get_list_or_404(Exp, patient=patient_id)
        # order_by必要かもしれん
        date_list = Inspection.objects.filter(patient=patient_id).order_by("inspection_date").values_list("inspection_date", flat=True).distinct()
        item_list = ["ALB","BUN","CRE","CRP","Ca","Cl","IP","K","Na","T-CHO","PCR", "TP"]
        inspection_array = [Inspection.objects.filter(patient=patient_id, inspection_item=item).order_by("inspection_item").values_list("inspection_value", flat=True) for item in item_list]
        # カラムの長さ調節のために、T-CHO -> TCHOに変更。
        item_list = ["ALB","BUN","CRE","CRP","Ca","Cl","IP","K","Na","TCHO","PCR", "TP"]
        # 指定した引数のresult_objが存在しない場合はNoneにする。
        result_obj = Result.objects.filter(patient=patient_obj, user=request.user).first()
        context = {
            "test_id": test_id,
            "exp_list": exp_list,
            "patient_obj": patient_obj,
            "patient_id" : patient_id,
            "result_obj" : result_obj,
            "inspection_array" : inspection_array,
            "item_list" : item_list,
            "date_list": date_list,
            }
        return render(request, "nephrosis/exp.html", context)

app/nephrosis/templates/nephrosis/base.html
{% load static %} {# staticファイルを使うときは load staticを追加する #}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap Sample</title>
    <!-- BootstrapのCSS読み込み -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- jQuery読み込み -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- BootstrapのJS読み込み -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    
  </head>
  <body>
    <div class="jumbotron">
        <h5> <a href="{% url 'nephrosis:index' %}">ネフローゼ発症予測支援システム</a> </h5>
        {% if request.user.is_authenticated %}
          <span>UserName : {{request.user.username}}  </span>
          <div class="pull-right"> <a href="{% url 'logout' %}">Log out</a></div>
        {% endif %}
    </div>
    {% block body %}
    {% endblock %}
  </body>
</html>

app/nephrosis/templates/nephrosis/detail.html
{% extends "nephrosis/base.html" %}

{% block body %}
Paitent Detail {{ patient_id }}
{% endblock %}

app/nephrosis/templates/nephrosis/exp.html
{% extends "nephrosis/base.html" %}
{% load static %} {# staticファイルを使うときは load staticを追加する #}

{% block body %}
<style type="text/css">
    .row-eq-height {
  display: flex;
  flex-wrap: wrap;
}
</style>

<div class="container">
    <div class="row">
        <h3> nephrosis {{patient_id}} </h3>
    </div>
    <div class="row m-3">
        {% comment %} インデックス用 {% endcomment %}
        <div class="col-md-1 h-100">
            <div>
                <table class="table">
                    <thead class="table-success">
                        <tr>
                            <th> ITEMS </th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for item in item_list %}
                        <tr>
                            <th class="table-info"> {{item}} </th>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
        {% comment %} 左半分 {% endcomment %}
        <div class="col-md-6 h-100">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead class="table-success">
                        <tr>
                            {% for date in date_list %}
                                <th> {{date | date:"Y/m/d"}} </th>
                            {% endfor %}
                        </tr>
                    </thead>
                    <tbody>
                    {% for date_inspection_values in inspection_array %}
                        <tr>
                            {% for inspection_value in date_inspection_values %}
                            <td> {{ inspection_value | floatformat:-3 |  default:"N/A" }} </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>


        {% comment %} 右半分 {% endcomment %}
        {% if test_id == "A" %}
            <div class="col-md-5">
            </div>
        {% else %}

            <div class="col-md-5">

                {% comment %} write predcition.js script {% endcomment %}
                <div class="row" style="height: 240px">

                    <div class="col-md-12">
                        <script type="text/javascript" charset="utf-8">
                            var predictionPlot = [{
                                    indexLabel: "nephs_proba",
                                    y: {{patient_obj.nephs_proba}},
                                    x: 0,
                                },{
                                    indexLabel: "nonnephs_proba",
                                    y: {{patient_obj.nonnephs_proba}},
                                    x: 1,
                                    }]
                        </script>
                        <div id="predictionContainer" style="height: 230px; width: 90%;"></div>
                        {% comment %} <div id="predictionContainer" style="height: 240px width: 80%";></div> {% endcomment %}
                    </div>
                </div>
                <div class="w-100"></div>
                
                {% comment %} generate LIME explanation {% endcomment %}
                {% if test_id == "C" %}
                    <div class="row" style="height: 360px">
                        {% comment %} write canvas.js script {% endcomment %}
                        {% comment %} <div class="w-100"></div> {% endcomment %}
                        <div class="col-md-12">
                            <script type="text/javascript" charset="utf-8">
                                var limePlot1 = []
                                {% for exp in exp_list %}
                                    limePlot1.push({
                                        indexLabel: "{{exp.cond_exp|safe}}",
                                        y: {{exp.contribution}},
                                        x: {{forloop.counter}},
                                    })
                                {% endfor %}
                            
                            </script>
                            <div id="chartContainer" style="height: 350px width: 90%"></div>
                        </div>
                    </div>
                {% endif %}

                <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
                <!-- <script src="{% static 'canvasjs/canvasjs.min.js' %}"></script> -->
                <script type="text/javascript" src="{% static 'myjs/prediction.js' %}" charset="utf-8"></script>
                <script type="text/javascript" src="{% static 'myjs/exp.js' %}" charset="utf-8"></script>
                
            </div>
        {% endif %}

    </div>


    {% comment %} POST入力フォーム {% endcomment %}
    <div class="row">
        {% comment %} <form name="is_nephs" action="./{{patient_id}}" method="POST"> {% endcomment %}
        <form name="is_nephs" action="{% url 'nephrosis:detail' test_id patient_id %}" method="POST">
            {% csrf_token %}
            <!-- !! 一旦userをosamuに固定 -->
            <input type="hidden" name="user" value="osamu">
            <input type="radio" id="id_nephs" name="is_nephs" value="nephs" checked>
            <label for="id_nephs"> Nephrosis </label>
            <input type="radio" id="id_non_nephs" name="is_nephs" value="non_nephs">
            <label for="id_non_nephs"> Non-Nephrosis </label>
            <input type="submit" value="決定">
        </form>
        <script type="text/javascript" src="{% static 'myjs/ajaxform.js' %}" charset="utf-8"></script>
        <br>
    </div>
    <div class="row">
        <span id="id_div_ajax_response">
            {% if result_obj == None %}
                ネフローゼの発症予測を行なってください。
            {% else %}
                現在の予測 : {{result_obj|yesno:"ネフローゼ, 非ネフローゼ" }}
            {% endif %}
        </span>
    </div>
</div>

<br>
<br>
{% endblock %}

app/nephrosis/templates/nephrosis/index.html
{% extends "nephrosis/base.html" %}

{% block body %}

<h3> テストID</h3>
<br>
{% if test_ids %}
    <div class="list-group">
    {% for test_id in test_ids %}
        <a href="{% url 'nephrosis:patients' test_id %}" class="list-group-item"> TEST {{ test_id }}</a>
    {% endfor %}
    </div>
{% else %}
    <p>No nephrosis are available.</p>
{% endif %} 
{% endblock  %}

app/nephrosis/templates/nephrosis/patients.html
{% extends "nephrosis/base.html" %}

{% block body %}

<h3> 患者一覧 </h3>
<br>
{% if patient_list %}
    <div class="list-group">
    {% for patient in patient_list %}
        <a href="{% url 'nephrosis:detail' test_id patient.id %}" class="list-group-item">{{ patient.patient_text }}</a>
    {% endfor %}
    </div>
{% else %}
    <p>No nephrosis are available.</p>
{% endif %} 
{% endblock  %}

app/nephrosis/templates/nephrosis/sample.html
{% extends "nephrosis/base.html" %}

{% block body %}
<table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th>#</th>
            <th>Column heading</th>
            <th>Column heading</th>
            <th>Column heading</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1</td>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr>
          <tr>
            <td>2</td>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr>
          <tr class="info">
            <td>3</td>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr>
          <tr class="success">
            <td>4</td>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr>
          <tr class="danger">
            <td>5</td>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr>
          <tr class="warning">
            <td>6</td>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr>
          <tr class="active">
            <td>7</td>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr>
        </tbody>
      </table> 
      
  {% endblock  %}
  

app/nephrosis/templates/nephrosis/signup.html
{% extends 'base.html' %}
 
{% block body %}
<h1>Sign up</h1>
<section class="common-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="submit">Sign up</button>
    </form>
</section>
{% endblock %}

app/nephrosis/templates/nephrosis/test.html
{% extends "nephrosis/base.html" %}

{% block body %}
is_ajax : {{is_ajax}}
<br>
<table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th>#</th>
            <th>Column heading</th>
            <th>Column heading</th>
            <th>Column heading</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1</td>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr>
          <tr>
            <td>2</td>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr>
          <tr class="info">
            <td>3</td>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr>
          <tr class="success">
            <td>4</td>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr>
          <tr class="danger">
            <td>5</td>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr>
          <tr class="warning">
            <td>6</td>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr>
          <tr class="active">
            <td>7</td>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr>
        </tbody>
      </table> 
      
  {% endblock  %}
  

app/templates/base.html
{% load static %} {# staticファイルを使うときは load staticを追加する #}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap Sample</title>
    <!-- BootstrapのCSS読み込み -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- jQuery読み込み -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- BootstrapのJS読み込み -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    
  </head>
  <body>
    <div class="jumbotron">
        <h5> ネフローゼ発症予測支援システム </h5>
    </div>
    {% block body %}
    {% endblock %}
  </body>
</html>